import type { Metadata } from "next";
import "@/styles/globals.css";

import SideNav from "../../components/layout/SideNav";
import { notoSansKr } from "../../src/lib/fonts";
import ClientWrapper from "./ClientWrapper"; // 👈 클라이언트 전용 영역 감싸는 컴포넌트
import Toast from "@/components/common/Toast";

export const metadata: Metadata = {
  title: "Orchedule",
  description: "Generated by create next app",
};

export default function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`${notoSansKr.className} min-h-screen`}>
      <div className="flex flex-col md:flex-row">
        <div className="hidden md:block fixed left-0 top-0 w-64 h-screen z-50">
          <SideNav />
        </div>
        <div className="md:ml-64 w-full">
          <Toast />
          <ClientWrapper>{children}</ClientWrapper>
        </div>
      </div>
    </div>
  );
}
